# Generated by Django 3.2.8 on 2021-11-11 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_aboutme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_link', models.CharField(max_length=255, null=True)),
                ('telegram_link', models.CharField(max_length=255, null=True)),
                ('linkedin_link', models.CharField(max_length=255, null=True)),
                ('facebook_link', models.CharField(max_length=255, null=True)),
                ('instagram_link', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
