# Generated by Django 3.2.8 on 2021-11-12 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_profil_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutme',
            name='image',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='image',
        ),
        migrations.AlterField(
            model_name='profil',
            name='image',
            field=models.ImageField(null=True, upload_to='static/images/'),
        ),
    ]
