# Generated by Django 3.2.8 on 2021-11-16 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20211112_1018'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profil',
        ),
    ]
